import nft1 from "@/assets/images/nft1.webp";
import nft2 from "@/assets/images/nft2.webp";
import nft3 from "@/assets/images/nft3.webp";
import nft4 from "@/assets/images/nft4.webp";
export const NftInfo = [
  {
    title: "Monkey Ape",
    creator: "@JSmith",
    status: "On Sale",
    price: "4.89 ETH",
    usd_price: "$6,547.86",
    likes: 341,
    button: "Buy Now",
    img: nft1,
  },
  {
    title: "Moonfall",
    creator: "@JSmith",
    status: "On Sale",
    price: "4.89 ETH",
    usd_price: "$6,547.86",
    likes: 341,
    button: "Buy Now",
    img: nft2,
  },
  {
    title: "Wired Human",
    creator: "@JSmith",
    status: "On Sale",
    price: "4.89 ETH",
    usd_price: "$6,547.86",
    likes: 341,
    button: "Buy Now",
    img: nft1,
  },
  {
    title: "Racer-To-Go",
    creator: "@JSmith",
    status: "On Sale",
    price: "4.89 ETH",
    usd_price: "$6,547.86",
    likes: 341,
    button: "Buy Now",
    img: nft3,
  },
  {
    title: "Digital Sunset",
    creator: "@ADoe",
    status: "On Sale",
    price: "3.50 ETH",
    usd_price: "$4,678.50",
    likes: 289,
    button: "Buy Now",
    img: nft4,
  },
  {
    title: "CryptoPunk",
    creator: "@CryptoArtist",
    status: "On Sale",
    price: "10.00 ETH",
    usd_price: "$13,350.00",
    likes: 512,
    button: "Buy Now",
    img: nft3,
  },
  {
    title: "Virtual Reality",
    creator: "@VRMaster",
    status: "On Sale",
    price: "7.25 ETH",
    usd_price: "$9,681.75",
    likes: 423,
    button: "Buy Now",
    img: nft2,
  },
  {
    title: "Pixel Art",
    creator: "@PixelArtist",
    status: "On Sale",
    price: "2.75 ETH",
    usd_price: "$3,671.25",
    likes: 198,
    button: "Buy Now",
    img: nft1,
  },
];
